import React from "react";
const { useState, useEffect, useCallback } = React;
import { C, SH } from "../constants.js";
import { Header, Centro, Stat, SectionTitle } from "../ui.jsx";
import { sb } from "../db.js";

const S = {
  card:{background:C.card,border:"1px solid "+C.line,borderRadius:14,padding:16,boxShadow:SH},
  input:{padding:"9px 11px",border:"1px solid "+C.line,borderRadius:8,background:C.paper,color:C.ink,width:"100%",boxSizing:"border-box",fontSize:13,height:38},
  btn:{padding:"9px 14px",border:0,borderRadius:8,background:C.brand,color:"#fff",fontWeight:700,cursor:"pointer"},
  btnGhost:{padding:"7px 12px",border:"1px solid "+C.line,borderRadius:8,background:"transparent",color:C.ink,fontWeight:600,cursor:"pointer"},
  th:{padding:"9px 10px",textAlign:"left",fontSize:11,textTransform:"uppercase",color:C.muted,borderBottom:"1px solid "+C.line},
  td:{padding:"9px 10px",fontSize:13,borderBottom:"1px solid "+C.line,verticalAlign:"top"},
};
const hoje=()=>new Date().toISOString().slice(0,10);
const num=n=>Number(n||0).toLocaleString("pt-BR",{maximumFractionDigits:2});
const ok=async p=>{const {data,error}=await p;if(error)throw error;return data};
const listar=t=>ok(sb.from(t).select("*").order("criado_em",{ascending:false}));
const inserir=(t,v)=>ok(sb.from(t).insert(v).select().single());
const rpc=(fn,args)=>ok(sb.rpc(fn,args));
const csv=(nome,rows)=>{
  const esc=v=>'"'+String(v??"").replace(/"/g,'""')+'"';
  const blob=new Blob([rows.map(r=>r.map(esc).join(";")).join("\n")],{type:"text/csv;charset=utf-8"});
  const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=nome;a.click();URL.revokeObjectURL(a.href);
};
function Campo({label,children}){return <label style={{display:"flex",flexDirection:"column",gap:6,fontSize:12,fontWeight:600,color:C.muted,minWidth:0}}>{label}{children}</label>}
function Tabela({cols,rows,vazio="Nenhum registro."}){return <div style={{overflow:"auto",...S.card,padding:0}}><table style={{width:"100%",borderCollapse:"collapse",minWidth:650}}><thead><tr>{cols.map(c=><th key={c[0]} style={S.th}>{c[1]}</th>)}</tr></thead><tbody>{!rows.length&&<tr><td colSpan={cols.length} style={S.td}>{vazio}</td></tr>}{rows.map((r,i)=><tr key={r.id||i}>{cols.map(c=><td key={c[0]} style={S.td}>{c[2]?c[2](r):r[c[0]]}</td>)}</tr>)}</tbody></table></div>}
function Form({children,onSubmit,label="Salvar"}){return <form onSubmit={e=>{e.preventDefault();onSubmit(new FormData(e.currentTarget),e.currentTarget)}} style={{...S.card,display:"grid",gridTemplateColumns:"repeat(auto-fill,minmax(190px,1fr))",gap:14,alignItems:"end"}}>{children}<div style={{gridColumn:"1 / -1",display:"flex",justifyContent:"flex-end",marginTop:2}}><button style={S.btn}>{label}</button></div></form>}
function Erro({msg}){return msg&&<div style={{padding:10,background:"#FBEAE3",color:C.clay,borderRadius:9,marginBottom:12}}>Erro: {msg}</div>}
function useDados(tabelas,prefixo){
  const [dados,setDados]=useState({}),[loading,setLoading]=useState(true),[erro,setErro]=useState("");
  const recarregar=useCallback(async()=>{try{const vals=await Promise.all(tabelas.map(listar));setDados(Object.fromEntries(tabelas.map((t,i)=>[t,vals[i]||[]])));setErro("")}catch(e){setErro(e.message||String(e))}finally{setLoading(false)}},[tabelas.join("|")]);
  useEffect(()=>{recarregar();const ch=sb.channel(prefixo+"-realtime");tabelas.forEach(t=>ch.on("postgres_changes",{event:"*",schema:"public",table:t},recarregar));ch.subscribe();return()=>{try{sb.removeChannel(ch)}catch(e){}}},[recarregar]);
  return {dados,loading,erro,recarregar,setErro};
}
function Shell({titulo,eyebrow,tabs,tab,setTab,onSair,children}){return <div style={{minHeight:"100vh",paddingBottom:60}}><Header titulo={titulo} eyebrow={eyebrow} tabs={tabs} tab={tab} setTab={setTab} onSair={onSair}/><main style={{maxWidth:1080,margin:"0 auto",padding:"0 20px"}}>{children}</main></div>}

const TPLUV=["pluv_pontos","pluv_leituras"];
export function Pluviometria({onSair,nome}){
  const [tab,setTab]=useState("leituras");const {dados,loading,erro,recarregar,setErro}=useDados(TPLUV,"pluv");
  const pontos=dados.pluv_pontos||[], leituras=dados.pluv_leituras||[], mapa=Object.fromEntries(pontos.map(x=>[x.id,x]));
  if(loading)return <Centro txt="Carregando pluviometria…"/>;
  const salvarPonto=async(f,el)=>{try{await inserir("pluv_pontos",{nome:f.get("nome"),codigo:f.get("codigo"),localizacao:f.get("localizacao"),latitude:f.get("latitude")||null,longitude:f.get("longitude")||null,ativo:true});el.reset();recarregar()}catch(e){setErro(e.message)}};
  const salvarLeitura=async(f,el)=>{try{await inserir("pluv_leituras",{ponto_id:f.get("ponto_id"),data:f.get("data"),hora:f.get("hora")||"07:00",precipitacao_mm:Number(f.get("precipitacao_mm")),responsavel:nome,observacao:f.get("observacao")});el.reset();recarregar()}catch(e){setErro(e.message)}};
  const total=leituras.reduce((s,x)=>s+Number(x.precipitacao_mm||0),0),max=leituras.reduce((m,x)=>Math.max(m,Number(x.precipitacao_mm||0)),0);
  return <Shell titulo="Pluviometria" eyebrow="Sementes Veneza · Medição pluviométrica" tabs={[["leituras","Medições"],["pontos","Pontos"],["relatorios","Relatórios"]]} tab={tab} setTab={setTab} onSair={onSair}><Erro msg={erro}/>
    {tab==="leituras"&&<><SectionTitle>Nova medição</SectionTitle><Form onSubmit={salvarLeitura}><Campo label="Ponto"><select name="ponto_id" required style={S.input}><option value="">Selecione</option>{pontos.filter(x=>x.ativo).map(x=><option key={x.id} value={x.id}>{x.codigo} · {x.nome}</option>)}</select></Campo><Campo label="Data"><input name="data" type="date" required defaultValue={hoje()} style={S.input}/></Campo><Campo label="Hora"><input name="hora" type="time" defaultValue="07:00" style={S.input}/></Campo><Campo label="Precipitação (mm)"><input name="precipitacao_mm" type="number" min="0" step=".1" required style={S.input}/></Campo><Campo label="Observação"><input name="observacao" style={S.input}/></Campo></Form><SectionTitle>Histórico</SectionTitle><Tabela rows={leituras} cols={[["data","Data"],["ponto","Ponto",x=>mapa[x.ponto_id]?.nome||"—"],["precipitacao_mm","Chuva",x=>num(x.precipitacao_mm)+" mm"],["responsavel","Responsável"],["observacao","Observação"]]}/></>}
    {tab==="pontos"&&<><SectionTitle>Novo ponto</SectionTitle><Form onSubmit={salvarPonto}><Campo label="Código"><input name="codigo" required style={S.input}/></Campo><Campo label="Nome"><input name="nome" required style={S.input}/></Campo><Campo label="Localização"><input name="localizacao" style={S.input}/></Campo><Campo label="Latitude"><input name="latitude" type="number" step="any" style={S.input}/></Campo><Campo label="Longitude"><input name="longitude" type="number" step="any" style={S.input}/></Campo></Form><SectionTitle>Pontos cadastrados</SectionTitle><Tabela rows={pontos} cols={[["codigo","Código"],["nome","Nome"],["localizacao","Localização"],["latitude","Latitude"],["longitude","Longitude"],["ativo","Status",x=>x.ativo?"Ativo":"Inativo"]]}/></>}
    {tab==="relatorios"&&<><div style={{display:"flex",gap:12,flexWrap:"wrap"}}><Stat rotulo="Chuva acumulada" valor={num(total)+" mm"}/><Stat rotulo="Maior medição" valor={num(max)+" mm"}/><Stat rotulo="Medições" valor={leituras.length}/><Stat rotulo="Pontos ativos" valor={pontos.filter(x=>x.ativo).length}/></div><SectionTitle>Exportação</SectionTitle><button style={S.btn} onClick={()=>csv("pluviometria.csv",[["Data","Ponto","mm","Responsável","Observação"],...leituras.map(x=>[x.data,mapa[x.ponto_id]?.nome,x.precipitacao_mm,x.responsavel,x.observacao])])}>Baixar CSV</button></>}
  </Shell>
}

const COMBUSTIVEIS=[["diesel","Diesel"],["gasolina","Gasolina"],["etanol","Etanol"],["gas","Gás"]];
const rotuloQtd=un=>un&&un!=="L"?"Quantidade ("+un+")":"Quantidade (L)";
const TCOMB=["comb_veiculos","comb_tanques","comb_abastecimentos","comb_entradas"];
export function Abastecimento({onSair,nome}){
  const [tab,setTab]=useState("abastecimentos");const {dados,loading,erro,recarregar,setErro}=useDados(TCOMB,"comb");
  const [tanqueAbs,setTanqueAbs]=useState(""),[tanqueEnt,setTanqueEnt]=useState(""),[combTanque,setCombTanque]=useState("diesel"),[unidTanque,setUnidTanque]=useState("L");
  const veiculos=dados.comb_veiculos||[],tanques=dados.comb_tanques||[],abs=dados.comb_abastecimentos||[],entradas=dados.comb_entradas||[];
  const vm=Object.fromEntries(veiculos.map(x=>[x.id,x])),tm=Object.fromEntries(tanques.map(x=>[x.id,x]));
  if(loading)return <Centro txt="Carregando abastecimentos…"/>;
  const nomeComb=c=>COMBUSTIVEIS.find(x=>x[0]===c)?.[1]||c;
  const addVeiculo=async(f,e)=>{try{await inserir("comb_veiculos",{identificacao:f.get("identificacao"),placa:f.get("placa"),tipo:f.get("tipo"),combustivel:f.get("combustivel"),ativo:true});e.reset();recarregar()}catch(x){setErro(x.message)}};
  const addTanque=async(f,e)=>{try{await inserir("comb_tanques",{nome:f.get("nome"),combustivel:f.get("combustivel"),unidade:f.get("unidade")||"L",capacidade_l:Number(f.get("capacidade_l")),saldo_l:Number(f.get("saldo_l")||0),ativo:true});e.reset();setCombTanque("diesel");setUnidTanque("L");recarregar()}catch(x){setErro(x.message)}};
  const addAbs=async(f,e)=>{try{await rpc("comb_registrar_abastecimento",{p_veiculo_id:f.get("veiculo_id"),p_tanque_id:f.get("tanque_id"),p_data:f.get("data"),p_quantidade:Number(f.get("quantidade")),p_odometro:f.get("odometro")?Number(f.get("odometro")):null,p_observacao:f.get("observacao")||null});e.reset();setTanqueAbs("");recarregar()}catch(x){setErro(x.message)}};
  const addEntrada=async(f,e)=>{try{await rpc("comb_registrar_entrada",{p_tanque_id:f.get("tanque_id"),p_data:f.get("data"),p_quantidade:Number(f.get("quantidade")),p_fornecedor:f.get("fornecedor")||null,p_documento:f.get("documento")||null,p_responsavel:f.get("responsavel")||nome,p_observacao:f.get("observacao")||null});e.reset();setTanqueEnt("");recarregar()}catch(x){setErro(x.message)}};
  const qtd=abs.reduce((s,x)=>s+Number(x.litros||0),0),qtdEnt=entradas.reduce((s,x)=>s+Number(x.quantidade||0),0);
  return <Shell titulo="Abastecimento" eyebrow="Sementes Veneza · Combustíveis (uso interno)" tabs={[["abastecimentos","Abastecimentos"],["entradas","Entrada nos tanques"],["veiculos","Veículos"],["tanques","Tanques"],["relatorios","Relatórios"]]} tab={tab} setTab={setTab} onSair={onSair}><Erro msg={erro}/>
    {tab==="abastecimentos"&&<><SectionTitle>Novo abastecimento</SectionTitle><Form onSubmit={addAbs}><Campo label="Veículo/equipamento"><select name="veiculo_id" required style={S.input}><option value="">Selecione</option>{veiculos.filter(x=>x.ativo).map(x=><option key={x.id} value={x.id}>{x.identificacao}{x.placa?" · "+x.placa:""} ({nomeComb(x.combustivel)})</option>)}</select></Campo><Campo label="Tanque"><select name="tanque_id" required value={tanqueAbs} onChange={e=>setTanqueAbs(e.target.value)} style={S.input}><option value="">Selecione</option>{tanques.filter(x=>x.ativo).map(x=><option key={x.id} value={x.id}>{x.nome} ({nomeComb(x.combustivel)} · {num(x.saldo_l)} {x.unidade})</option>)}</select></Campo><Campo label="Data"><input name="data" type="date" required defaultValue={hoje()} style={S.input}/></Campo><Campo label={rotuloQtd(tm[tanqueAbs]?.unidade)}><input name="quantidade" type="number" min=".01" step=".01" required style={S.input}/></Campo><Campo label="Odômetro/Horímetro"><input name="odometro" type="number" min="0" step=".1" style={S.input}/></Campo><Campo label="Observação"><input name="observacao" style={S.input}/></Campo></Form><SectionTitle>Histórico</SectionTitle><Tabela rows={abs} cols={[["data","Data"],["veiculo","Veículo",x=>vm[x.veiculo_id]?.identificacao||"—"],["tanque","Tanque",x=>tm[x.tanque_id]?.nome||"—"],["litros","Quantidade",x=>num(x.litros)+" "+(x.unidade||"L")],["odometro","Odômetro",x=>x.odometro?num(x.odometro):"—"]]}/></>}
    {tab==="entradas"&&<><SectionTitle>Reabastecer tanque (fornecedor externo)</SectionTitle><Form onSubmit={addEntrada}><Campo label="Tanque"><select name="tanque_id" required value={tanqueEnt} onChange={e=>setTanqueEnt(e.target.value)} style={S.input}><option value="">Selecione</option>{tanques.filter(x=>x.ativo).map(x=><option key={x.id} value={x.id}>{x.nome} ({nomeComb(x.combustivel)} · capacidade {num(x.capacidade_l)} {x.unidade})</option>)}</select></Campo><Campo label="Data"><input name="data" type="date" required defaultValue={hoje()} style={S.input}/></Campo><Campo label={rotuloQtd(tm[tanqueEnt]?.unidade)}><input name="quantidade" type="number" min=".01" step=".01" required style={S.input}/></Campo><Campo label="Fornecedor"><input name="fornecedor" style={S.input}/></Campo><Campo label="Documento"><input name="documento" style={S.input}/></Campo><Campo label="Responsável"><input name="responsavel" defaultValue={nome} style={S.input}/></Campo><Campo label="Observação"><input name="observacao" style={S.input}/></Campo></Form><SectionTitle>Histórico de entradas</SectionTitle><Tabela rows={entradas} cols={[["data","Data"],["tanque","Tanque",x=>tm[x.tanque_id]?.nome||"—"],["quantidade","Quantidade",x=>num(x.quantidade)+" "+(x.unidade||"L")],["fornecedor","Fornecedor"],["documento","Documento"],["responsavel","Responsável"]]}/></>}
    {tab==="veiculos"&&<><SectionTitle>Novo veículo/equipamento</SectionTitle><Form onSubmit={addVeiculo}><Campo label="Identificação"><input name="identificacao" required style={S.input}/></Campo><Campo label="Placa"><input name="placa" style={S.input}/></Campo><Campo label="Tipo"><input name="tipo" placeholder="Caminhão, trator, empilhadeira…" style={S.input}/></Campo><Campo label="Combustível"><select name="combustivel" style={S.input}>{COMBUSTIVEIS.map(c=><option key={c[0]} value={c[0]}>{c[1]}</option>)}</select></Campo></Form><SectionTitle>Frota</SectionTitle><Tabela rows={veiculos} cols={[["identificacao","Identificação"],["placa","Placa"],["tipo","Tipo"],["combustivel","Combustível",x=>nomeComb(x.combustivel)],["ativo","Status",x=>x.ativo?"Ativo":"Inativo"]]}/></>}
    {tab==="tanques"&&<><SectionTitle>Novo tanque</SectionTitle><Form onSubmit={addTanque}><Campo label="Nome"><input name="nome" required style={S.input}/></Campo><Campo label="Combustível"><select name="combustivel" value={combTanque} onChange={e=>{setCombTanque(e.target.value);setUnidTanque(e.target.value==="gas"?"m3":"L")}} style={S.input}>{COMBUSTIVEIS.map(c=><option key={c[0]} value={c[0]}>{c[1]}</option>)}</select></Campo><Campo label="Unidade"><select name="unidade" value={unidTanque} onChange={e=>setUnidTanque(e.target.value)} style={S.input}><option value="L">Litros (L)</option><option value="m3">Metros cúbicos (m³)</option><option value="kg">Quilogramas (kg)</option></select></Campo><Campo label="Capacidade"><input name="capacidade_l" type="number" min="0" required style={S.input}/></Campo><Campo label="Saldo inicial"><input name="saldo_l" type="number" min="0" style={S.input}/></Campo></Form><SectionTitle>Tanques</SectionTitle><Tabela rows={tanques} cols={[["nome","Nome"],["combustivel","Combustível",x=>nomeComb(x.combustivel)],["capacidade_l","Capacidade",x=>num(x.capacidade_l)+" "+x.unidade],["saldo_l","Saldo",x=>num(x.saldo_l)+" "+x.unidade],["nivel","Nível",x=>x.capacidade_l?Math.round(x.saldo_l/x.capacidade_l*100)+"%":"—"]]}/></>}
    {tab==="relatorios"&&<><div style={{display:"flex",gap:12,flexWrap:"wrap"}}><Stat rotulo="Abastecido (registros)" valor={abs.length}/><Stat rotulo="Volume total abastecido" valor={num(qtd)}/><Stat rotulo="Entradas nos tanques" valor={entradas.length}/><Stat rotulo="Volume total recebido" valor={num(qtdEnt)}/></div><SectionTitle>Exportação</SectionTitle><div style={{display:"flex",gap:10}}><button style={S.btn} onClick={()=>csv("abastecimentos.csv",[["Data","Veículo","Tanque","Combustível","Quantidade","Unidade","Odômetro"],...abs.map(x=>[x.data,vm[x.veiculo_id]?.identificacao,tm[x.tanque_id]?.nome,x.combustivel,x.litros,x.unidade,x.odometro])])}>Baixar CSV de abastecimentos</button><button style={S.btnGhost} onClick={()=>csv("entradas_combustivel.csv",[["Data","Tanque","Combustível","Quantidade","Unidade","Fornecedor","Documento","Responsável"],...entradas.map(x=>[x.data,tm[x.tanque_id]?.nome,x.combustivel,x.quantidade,x.unidade,x.fornecedor,x.documento,x.responsavel])])}>Baixar CSV de entradas</button></div></>}
  </Shell>
}

const UNIDADES_PADRAO=[["un","Unidade"],["kg","Quilograma"],["L","Litro"],["m","Metro"],["cx","Caixa"],["pct","Pacote"]];
const TALM=["alm_itens","alm_movimentacoes","alm_inventarios","alm_inventario_itens","alm_categorias","alm_unidades"];
export function Almoxarifado({onSair,nome}){
  const [tab,setTab]=useState("movimentacoes");const {dados,loading,erro,recarregar,setErro}=useDados(TALM,"alm");
  const [invSel,setInvSel]=useState(null);
  const itens=dados.alm_itens||[],movs=dados.alm_movimentacoes||[],invs=dados.alm_inventarios||[],conts=dados.alm_inventario_itens||[];
  const categorias=dados.alm_categorias||[],unidades=dados.alm_unidades||[];
  const im=Object.fromEntries(itens.map(x=>[x.id,x]));
  if(loading)return <Centro txt="Carregando almoxarifado…"/>;
  const saldo=id=>movs.filter(x=>x.item_id===id).reduce((s,x)=>s+(x.tipo==="entrada"?1:-1)*Number(x.quantidade||0),0);
  const addCategoria=async(f,e)=>{try{await inserir("alm_categorias",{nome:f.get("nome"),tag:String(f.get("tag")||"").toUpperCase()});e.reset();recarregar()}catch(x){setErro(x.message)}};
  const addUnidade=async(f,e)=>{try{await inserir("alm_unidades",{nome:f.get("nome"),sigla:f.get("sigla")});e.reset();recarregar()}catch(x){setErro(x.message)}};
  const addItem=async(f,e)=>{try{await rpc("alm_criar_item",{p_nome:f.get("nome"),p_categoria_id:f.get("categoria_id"),p_unidade_id:f.get("unidade_id"),p_estoque_minimo:Number(f.get("estoque_minimo")||0)});e.reset();recarregar()}catch(x){setErro(x.message)}};
  const addMov=async(f,e)=>{try{await rpc("alm_registrar_movimentacao",{p_item_id:f.get("item_id"),p_data:f.get("data"),p_tipo:f.get("tipo"),p_quantidade:Number(f.get("quantidade")),p_documento:f.get("documento")||null,p_responsavel:f.get("responsavel")||nome,p_observacao:f.get("observacao")||null});e.reset();recarregar()}catch(x){setErro(x.message)}};
  const abrirInv=async(f,e)=>{try{const id=await rpc("alm_abrir_inventario",{p_data:f.get("data"),p_responsavel:f.get("responsavel")||nome,p_observacao:f.get("observacao")||null});e.reset();setInvSel(id);recarregar()}catch(x){setErro(x.message)}};
  const contar=async(id,valor)=>{try{await rpc("alm_atualizar_contagem",{p_inventario_item_id:id,p_contagem:Number(valor)});recarregar()}catch(x){setErro(x.message)}};
  const concluirInv=async id=>{if(!confirm("Concluir este inventário? As diferenças viram movimentações de ajuste automáticas."))return;try{await rpc("alm_concluir_inventario",{p_inventario_id:id,p_responsavel:nome});setInvSel(null);recarregar()}catch(x){setErro(x.message)}};
  const total=itens.reduce((s,x)=>s+saldo(x.id),0),baixos=itens.filter(x=>saldo(x.id)<Number(x.estoque_minimo||0));
  const invAtual=invs.find(x=>x.id===invSel),itensInv=conts.filter(c=>c.inventario_id===invSel);
  return <Shell titulo="Almoxarifado" eyebrow="Sementes Veneza · Estoque" tabs={[["movimentacoes","Movimentações"],["itens","Itens"],["categorias","Categorias & unidades"],["inventarios","Inventários"],["relatorios","Relatórios"]]} tab={tab} setTab={setTab} onSair={onSair}><Erro msg={erro}/>
    {tab==="movimentacoes"&&<><SectionTitle>Nova movimentação</SectionTitle><Form onSubmit={addMov}><Campo label="Item"><select name="item_id" required style={S.input}><option value="">Selecione</option>{itens.filter(x=>x.ativo).map(x=><option key={x.id} value={x.id}>{x.codigo} · {x.nome}</option>)}</select></Campo><Campo label="Data"><input name="data" type="date" required defaultValue={hoje()} style={S.input}/></Campo><Campo label="Tipo"><select name="tipo" style={S.input}><option value="entrada">Entrada</option><option value="saida">Saída</option></select></Campo><Campo label="Quantidade"><input name="quantidade" type="number" min=".001" step=".001" required style={S.input}/></Campo><Campo label="Documento"><input name="documento" style={S.input}/></Campo><Campo label="Responsável"><input name="responsavel" defaultValue={nome} style={S.input}/></Campo><Campo label="Observação"><input name="observacao" style={S.input}/></Campo></Form><SectionTitle>Histórico</SectionTitle><Tabela rows={movs} cols={[["data","Data"],["item","Item",x=>im[x.item_id]?.nome||"—"],["tipo","Tipo",x=>x.tipo==="entrada"?"Entrada":"Saída"],["quantidade","Quantidade",x=>num(x.quantidade)+" "+(im[x.item_id]?.unidade||"")],["origem","Origem",x=>x.origem==="inventario"?"Ajuste de inventário":"Manual"],["responsavel","Responsável"]]}/></>}
    {tab==="itens"&&<><SectionTitle>Novo item</SectionTitle><Form onSubmit={addItem}><Campo label="Nome"><input name="nome" required style={S.input}/></Campo><Campo label="Categoria"><select name="categoria_id" required style={S.input}><option value="">Selecione</option>{categorias.filter(x=>x.ativo).map(x=><option key={x.id} value={x.id}>{x.nome} ({x.tag})</option>)}</select></Campo><Campo label="Unidade"><select name="unidade_id" required style={S.input}><option value="">Selecione</option>{unidades.filter(x=>x.ativo).map(x=><option key={x.id} value={x.id}>{x.nome} ({x.sigla})</option>)}</select></Campo><Campo label="Estoque mínimo"><input name="estoque_minimo" type="number" min="0" step=".001" style={S.input}/></Campo></Form>{!categorias.length&&<div style={{marginTop:10,fontSize:12,color:C.muted}}>Cadastre uma categoria na aba "Categorias & unidades" antes de criar itens — o código é gerado automaticamente a partir da tag dela.</div>}<SectionTitle>Estoque atual</SectionTitle><Tabela rows={itens} cols={[["codigo","Código"],["nome","Item"],["categoria","Categoria"],["saldo","Saldo",x=><b style={{color:saldo(x.id)<Number(x.estoque_minimo||0)?C.clay:C.ink}}>{num(saldo(x.id))} {x.unidade}</b>],["estoque_minimo","Mínimo",x=>num(x.estoque_minimo)+" "+x.unidade]]}/></>}
    {tab==="categorias"&&<><SectionTitle>Nova categoria</SectionTitle><Form onSubmit={addCategoria}><Campo label="Nome"><input name="nome" required style={S.input}/></Campo><Campo label="Tag (2-8 letras/números, ex: EPI)"><input name="tag" required maxLength={8} pattern="[A-Za-z0-9]{2,8}" title="2 a 8 letras/números" style={{...S.input,textTransform:"uppercase"}}/></Campo></Form><div style={{marginTop:10,fontSize:12,color:C.muted}}>Cada novo item da categoria recebe automaticamente o código TAG+número, ex.: EPI0001, EPI0002…</div><SectionTitle>Categorias cadastradas</SectionTitle><Tabela rows={categorias} cols={[["tag","Tag"],["nome","Nome"],["proximo_numero","Próximo código",x=>x.tag+String(x.proximo_numero).padStart(4,"0")],["ativo","Status",x=>x.ativo?"Ativa":"Inativa"]]}/><SectionTitle>Nova unidade de medida</SectionTitle><Form onSubmit={addUnidade}><Campo label="Nome"><input name="nome" required list="alm-un-sugestoes" style={S.input}/></Campo><Campo label="Sigla"><input name="sigla" required maxLength={10} style={S.input}/></Campo><datalist id="alm-un-sugestoes">{UNIDADES_PADRAO.map(u=><option key={u[0]} value={u[1]}/>)}</datalist></Form><SectionTitle>Unidades cadastradas</SectionTitle><Tabela rows={unidades} cols={[["sigla","Sigla"],["nome","Nome"],["ativo","Status",x=>x.ativo?"Ativa":"Inativa"]]}/></>}
    {tab==="inventarios"&&<><SectionTitle>Abrir inventário</SectionTitle><Form onSubmit={abrirInv} label="Abrir inventário"><Campo label="Data"><input name="data" type="date" required defaultValue={hoje()} style={S.input}/></Campo><Campo label="Responsável"><input name="responsavel" defaultValue={nome} style={S.input}/></Campo><Campo label="Observação"><input name="observacao" style={S.input}/></Campo></Form><SectionTitle>Inventários</SectionTitle><Tabela rows={invs} cols={[["data","Data"],["status","Status",x=>x.status==="aberto"?"Aberto":"Concluído"],["responsavel","Responsável"],["itens","Itens",x=>conts.filter(c=>c.inventario_id===x.id).length],["acao","Ação",x=><button style={S.btnGhost} onClick={()=>setInvSel(x.id)}>{x.status==="aberto"?"Contar itens":"Ver contagem"}</button>]]}/>
      {invAtual&&<><SectionTitle>Contagem — {invAtual.data} ({invAtual.status==="aberto"?"em andamento":"concluído"})</SectionTitle><Tabela rows={itensInv} vazio="Nenhum item ativo no momento da abertura." cols={[["item","Item",x=>im[x.item_id]?.codigo+" · "+(im[x.item_id]?.nome||"—")],["saldo_sistema","Saldo no sistema",x=>num(x.saldo_sistema)+" "+(im[x.item_id]?.unidade||"")],["contagem_fisica","Contagem física",x=><input type="number" step=".001" defaultValue={x.contagem_fisica} disabled={invAtual.status!=="aberto"} style={{...S.input,maxWidth:140}} onBlur={e=>contar(x.id,e.target.value)}/>],["diferenca","Diferença",x=><b style={{color:Number(x.diferenca)===0?C.ink:C.clay}}>{num(x.diferenca)}</b>]]}/>{invAtual.status==="aberto"&&<div style={{marginTop:12}}><button style={S.btn} onClick={()=>concluirInv(invAtual.id)}>Concluir inventário</button></div>}</>}
    </>}
    {tab==="relatorios"&&<><div style={{display:"flex",gap:12,flexWrap:"wrap"}}><Stat rotulo="Itens cadastrados" valor={itens.length}/><Stat rotulo="Saldo total" valor={num(total)}/><Stat rotulo="Abaixo do mínimo" valor={baixos.length}/><Stat rotulo="Movimentações" valor={movs.length}/></div><SectionTitle>Itens abaixo do mínimo</SectionTitle><Tabela rows={baixos} cols={[["codigo","Código"],["nome","Item"],["saldo","Saldo",x=>num(saldo(x.id))+" "+x.unidade],["estoque_minimo","Mínimo",x=>num(x.estoque_minimo)+" "+x.unidade]]}/><SectionTitle>Exportação</SectionTitle><button style={S.btn} onClick={()=>csv("estoque.csv",[["Código","Item","Categoria","Unidade","Saldo","Mínimo"],...itens.map(x=>[x.codigo,x.nome,x.categoria,x.unidade,saldo(x.id),x.estoque_minimo])])}>Baixar CSV</button></>}
  </Shell>
}
